### PR TITLE
feat: allow action on dashboard by tag

### PR DESCRIPTION
**Pull request by rasta-rocket**
Hi folks,

Little contribution that allows to list or import dashboards per tags

Don't hesitate if you have any questions

Cheers :wink:

### CODE REVIEW

**Comment by safaci2000** [comment]
Hey, sorry I just noticed this PR.  I'll take a look at this shortly.

**Comment by safaci2000** [comment]
@rasta-rocket A few minor comments.  I need to set this up and run through the code, but a few asks. 

1. Can you update the documentation to reflect the changes you're introducing.  (Nice to have, but I'll call it optional)
2. Mind adding a unit test, you can add some new sample JSONs or modify some of the current ones if you need to in order to let you filter by tag.

**Comment by safaci2000** [comment]
If you can add a small test and fix the CI issues with linting.  (try running golangci-lint run against the code base), this looks good to merge.

**Comment by rasta-rocket** [comment]
Hey @safaci2000 thx for the review 👍 

I just did the changes asked, let me know if it is ok or not 😉 

Cheers

**Review by safaci2000 — APPROVED** [review]
LGTM

**Pull request merged**
